Initial work
JustinKuli/grc-test-summaries pull request #1
Opened 2021-12-15 20:34 UTC by JustinKuli

2021-12-15 22:10 UTC, mprahl requested changes
This looks great! I left a lot of optional comments to teach you some of the "Pythonic" approaches but you can choose to not implement them.

2021-12-15 22:10 UTC, mprahl commented on main.py
> +    def __init__(self, domain, cause):
It'd be cleaner if you called the parent class' `__init__` method with `super` to not duplicate some of the code.

2021-12-15 22:10 UTC, mprahl commented on main.py
> +        # Example:
Could you move this comment to above `self.regex =`?

2021-12-15 22:10 UTC, mprahl commented on tekton/Task.scrape-analyze-upload-tests.yaml
> +apiVersion: tekton.dev/v1beta1
Could you please run a YAML autoformatter on this file?

2021-12-16 19:44 UTC, JustinKuli commented on main.py
> +        with open("headers-" + output_name, "w") as headerfile:
If you wanted to read the csv locally, it would help to have the headers. But the tool that currently gets the data from the files in S3 doesn't respect the headers (despite configuring it with `skip-headers=true`) - it thinks they're just another data row.

Looking at it now, it doesn't make much sense as a separate file - I will put it in the main csv instead.

2021-12-16 19:44 UTC, JustinKuli commented on Containerfile
> +FROM quay.io/fedora/fedora:34
I had a problem building using that as a base on my computer, but I think it's a Mac issue. Good suggestion.

2021-12-16 19:59 UTC, JustinKuli commented on main.py
> +        verify=False,
The example I had been working off didn't mention it, so I wasn't sure where to get/put the cert bundle. I'll make this configurable.

2021-12-16 20:40 UTC, JustinKuli commented on main.py
> +            last_not_found_yet = False
Even better will be to just break, great suggestion, `last_not_found_yet` isn't really necessary

2021-12-16 20:44 UTC, JustinKuli commented on main.py
> +            last_not_found_yet = False
Nevermind, it's a nested loop, and you can't break out of both in python

2021-12-16 20:46 UTC, JustinKuli commented on main.py
> +CSV_FIELD_NAMES = [
I personally prefer it closer to the place where it is used most: inside the BuildInfo methods.

2021-12-16 21:09 UTC, JustinKuli commented on main.py
> +        for j in self.failing_jobs:
I more wanted "build" success than individual job success. Things (like our fast-forward job) depend on the entire build succeeding - if 4/5 jobs are always passing, but 1 is always failing, I think assigning an 80% success rate would be very misguiding.

It's not exactly fair to weigh failures by number of jobs and successes by number of builds, but I think it is useful.

2021-12-16 21:14 UTC, JustinKuli commented on main.py
> +        return f"unknown-{number}"
I don't think it's so bad if the data isn't quite labelled correctly (as in, if we add a new job to the build, now something might fail that we don't really know about, it would get something like `unknown-10`).

We can't identify if we changed job orders, and the names are wrong, so there are easily situations where stuff is mislabelled that we can't know about here to throw an exception on.

I personally would rather keep sending data (with what I see as small imperfections), which can be analyzed on a best-effort basis, rather than shut the system down until we come and fix it.

2021-12-16 21:15 UTC, JustinKuli commented on main.py
> +    job_names = {
But then it's a global, and not used anywhere else. You're right, but it's a trade-off.

2021-12-16 21:17 UTC, JustinKuli commented on main.py
> +        return f"unknown-{number}"
See above. There are easily situations things will be out of date and we can't throw an exception. I don't feel this situation is bad enough to fail the script.

2021-12-16 21:31 UTC, JustinKuli commented on tekton/cronjob.yaml
> +            image: gcr.io/tekton-releases/dogfooding/tkn:latest
I looked, but couldn't find one. There isn't one associated with the release: https://github.com/tektoncd/cli/releases :(

2021-12-16 22:19 UTC, JustinKuli commented
@mprahl, no rush, but if you have a chance to re-review I would appreciate it. I implemented most of your comments.

2021-12-17 16:38 UTC, mprahl requested changes

2021-12-17 16:38 UTC, mprahl commented on Containerfile
> +RUN curl google.com
This doesn't look right.  :laughing:

2021-12-17 17:03 UTC, JustinKuli commented on Containerfile
> +RUN curl google.com
😅

2021-12-17 17:11 UTC, mprahl approved these changes
Nice job!

2021-12-17 17:27 UTC, merged